// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs1VFknDwk7CxsG6qNV1NYrCL0JK2RKA4',
    appId: '1:72734802181:web:39a77b469b76e46c10b76c',
    messagingSenderId: '72734802181',
    projectId: 'festival-tracker-221ca',
    authDomain: 'festival-tracker-221ca.firebaseapp.com',
    storageBucket: 'festival-tracker-221ca.firebasestorage.app',
    measurementId: 'G-NXGFB50B35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzw6icHHaScvSSJbpiXufUVcE1iLcgHBk',
    appId: '1:72734802181:android:a1be959f9fc755df10b76c',
    messagingSenderId: '72734802181',
    projectId: 'festival-tracker-221ca',
    storageBucket: 'festival-tracker-221ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECtwigk8IIAW_BWdsxY79p3czsvdiPXY',
    appId: '1:72734802181:ios:259f4e3666d4dca810b76c',
    messagingSenderId: '72734802181',
    projectId: 'festival-tracker-221ca',
    storageBucket: 'festival-tracker-221ca.firebasestorage.app',
    iosBundleId: 'com.cultureconnection.festmap.festmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDECtwigk8IIAW_BWdsxY79p3czsvdiPXY',
    appId: '1:72734802181:ios:41bc2ca55c0371c810b76c',
    messagingSenderId: '72734802181',
    projectId: 'festival-tracker-221ca',
    storageBucket: 'festival-tracker-221ca.firebasestorage.app',
    iosBundleId: 'com.cultureconnection.festmap.festmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs1VFknDwk7CxsG6qNV1NYrCL0JK2RKA4',
    appId: '1:72734802181:web:570bffd4f827318c10b76c',
    messagingSenderId: '72734802181',
    projectId: 'festival-tracker-221ca',
    authDomain: 'festival-tracker-221ca.firebaseapp.com',
    storageBucket: 'festival-tracker-221ca.firebasestorage.app',
    measurementId: 'G-04MZ55CQZF',
  );
}
